version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ../config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ../config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ../config/kibana/:/test_data

volumes:
  elastic-data:
    driver: local
