version: '3.3'

services:
  admin:
    image: dsecureme/vmc:1.2-RC-3
    restart: unless-stopped
    container_name: vmc_admin
    command: ["admin"]
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ../config/vmc/demo.yml:/etc/vmc/config.yml
      - ../config/vmc/:/test_data

  nginx:
    image: dsecureme/vmc-static-nginx:1.2-RC-3
    container_name: vmc_static
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - vmc_admin
    volumes:
      - ../config/vmc/demo.yml:/etc/vmc/config.yml
      - ../config/vmc/:/test_data

  worker:
    image: dsecureme/vmc:1.2-RC-3
    container_name: vmc_worker
    restart: unless-stopped
    command: ["worker"]
    depends_on:
      - vmc_admin
      - rabbitmq
      - redis
    volumes:
      - ../config/vmc/demo.yml:/etc/vmc/config.yml

  scheduler:
    image: dsecureme/vmc:1.2-RC-3
    container_name: vmc_scheduler
    restart: unless-stopped
    command: ["scheduler"]
    depends_on:
      - vmc_admin
      - rabbitmq
    volumes:
      - ../config/vmc/demo.yml:/etc/vmc/config.yml

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}
    env_file: ../.env

  redis:
    container_name: redis
    image: redis:${REDDIS_VERSION}


volumes:
  vmc-backup-data:
    driver: local