version: '3.3'

services:
  elastalert:
    image: jertel/elastalert2:${ELASTALERT_VERSION}
    container_name: elastalert
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    volumes:
      - ../config/elastalert/elastalert.yaml:/opt/elastalert/config.yaml
      - ../config/elastalert/rules:/opt/elastalert/rules
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f elastalert"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
