version: '3.3'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres-data:
    driver: local
