version: '3.3'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../.env

volumes:
  postgres-data:
    driver: local
