version: '3.3'

services:
  elastalert:
    image: bitsensor/elastalert:3.0.0-beta.1
    container_name: elastalert
    restart: unless-stopped
    depends_on:
      - kibana
      - elasticsearch
    ports:
      - "3030:3030"
      - "3333:3333"
    volumes:
      - ../config/elastalert/elastalert.yaml:/opt/elastalert/config.yaml
      - ../config/elastalert/elastalert.yaml:/opt/elastalert/config-test.yaml
      - ../config/elastalert/rules:/opt/elastalert/rules